# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 
# Title of the Site
title: 🔥Blazed & Confused🔥
# Description of the Site
description: Howd I get here... and who sent you?
# URL of Image of the Site
site-image: /assets/images/bluepurp.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 
bgtext: BlazeK1ng420
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/prism.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: xblazek1ng420@gmail.com
facebook_username: BlazeK1ng420
twitter_username: BlazeK1ng420
instagram_username: blazek1ng420
linkedin_username: 
github_username:  BlazeK1ng420
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: BlazeK1ng420 / ~Trevor~
# URL for the Image of the Author
author-image: https://lh3.googleusercontent.com/a/AAcHTtf-pbXpl_ammquCA2v2D8g9y1UdpSmL6WG0jWvkyiWm1Hdj=s288-c-no
# 60 Words About the Author
author-about: Will add later~
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/BlazeK1ng420

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
